config/routes.rb
Rails.application.routes.draw do
  get '/admin', to: "admin#index"
  get '/login', to: "access#new"
  post '/login', to: "access#create"
  delete '/exit', to: 'access#destroy'
  get 'access/new'
  get 'access/create'
  get 'access/destroy'
  get 'admin/index'
  resources :users
  resources :orders
  resources :lineitems
  resources :carts
  root "shopper#index", as: "shopper"
  get '/exit', to: 'sessions#destroy', as: :logout
  get 'shopper/index'
  resources :products
  resources :shopper do
	collection do
		get 'show_product' => 'shopper#show_product', as: :show_product
	end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/shopper_controller.rb
class ShopperController < ApplicationController
  include CurrentCart
  before_action :set_cart
  skip_before_action :authorize
  def index
	#if params[:search]
		#@products = Product.where('name LIKE ?', "%#{params[:search]}%")
	#else
	@products = Product.order(:name)
	#end
  end
  
  def show_product
	if params[:search]
		@products = Product.where('name LIKE ?', "%#{params[:search]}%")
	else
		@products = nil
	end
  end
end

app/helpers/shopper_helper.rb
module ShopperHelper
end

app/views/shopper/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<%= form_tag show_product_shopper_index_path, method: :get, class: 'search_bar' do %>
	<%= text_field_tag :search, params[:search], placeholder: "Search" %>
	<%= submit_tag "Search", name: nil %>
<% end %>

<h1>Product Catalog</h1>

<% @products.each do |product| %>
<div class="entry">
	<%= image_tag(product.image, class: 'img') %>
	<h3><%= product.name %></h3>
	<div class="price_line">
		<%= sanitize(product.description) %><br>
		<span class="price"><%= product.price %></span>
	</div>
	<%= button_to 'Add to Cart', lineitems_path(product_id: product), class: 'add_to_cart', remote:true %>
</div>
<% end %>
<%= link_to 'Back', shopper_path, id: 'back_shopper' %>

app/views/shopper/show_product.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<%= form_tag show_product_shopper_index_path, method: :get, class: 'search_bar' do %>
	<%= text_field_tag :search, params[:search], placeholder: "Search" %>
	<%= submit_tag "Search", name: nil %>
<% end %>

<h1>Product Catalog</h1>


<% @products.each do |product| %>
<div class="entry2">
	<%= image_tag(product.image, class: 'img') %>
	<h3><%= product.name %></h3>
	<div class="price_line">
		<%= sanitize(product.description) %><br>
		<span class="price"><%= product.price %></span>
	</div>
	<%= button_to 'Add to Cart', lineitems_path(product_id: product), class: 'add_to_cart', remote:true %>
</div>
<% end %>

<%= link_to 'Back', shopper_path, id: 'back_shopper' %>