config/routes.rb
Rails.application.routes.draw do
  get '/admin', to: "admin#index"
  get '/login', to: "access#new"
  post '/login', to: "access#create"
  delete '/exit', to: 'access#destroy'
  get 'access/new'
  get 'access/create'
  get 'access/destroy'
  get 'admin/index'
  resources :users
  resources :orders
  resources :lineitems
  resources :carts
  root "shopper#index", as: "shopper"
  get '/exit', to: 'sessions#destroy', as: :logout
  get 'shopper/index'
  resources :products
  resources :shopper do
	collection do
		get 'show_product' => 'shopper#show_product', as: :show_product
	end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoreApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller.controller_name%>">
	<div id="banner">
			<%= image_tag("logo.jpg") %>
			<%= @page_title || "Our Products" %>
	</div>
	
	<div id = "columns">
		<div id="side">
			<div id="cart">
				<%= render @cart %>
			</div>
			<ul>
				<li><a href="http://www....">Home</a></li>
				<li><a href="http://www..../faq">Questions</a></li>
				<li><a href="http://www..../news">News</a></li>
				<li><a href="http://www..../contact">Contact</a></li>
			</ul>
			
			<% if session[:user_id] %>
				<ul>
					<li><%= link_to 'Orders', orders_path %></li>
					<li><%= link_to 'Products', products_path %></li>
					<li><%= link_to 'Users', users_path %></li>
				</ul>
				<%= button_to 'Logout', logout_path, method: :delete %>
			<% end %>
		</div>
		
		<div id="main">
			<%= yield %>
		</div>
	</div>
  </body>
</html>